DROP SCHEMA IF EXISTS `RemoteDockerContainer`;
CREATE SCHEMA IF NOT EXISTS `RemoteDockerContainer`;
USE `RemoteDockerContainer`;


CREATE TABLE IF NOT EXISTS `USER` (
	`PORT` BIGINT AUTO_INCREMENT NOT NULL,
	`FULLNAME` NVARCHAR(100) NOT NULL,		
    `EMAIL` VARCHAR(40) NULL,
    
    PRIMARY KEY(`PORT`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;