DROP SCHEMA IF EXISTS `container_db`;
CREATE SCHEMA IF NOT EXISTS `container_db`;
USE `container_db`;


CREATE TABLE IF NOT EXISTS `USER` (
	`PORT` INT AUTO_INCREMENT NOT NULL,
	`FULL_NAME` NVARCHAR(100) NOT NULL,		
    `EMAIL` VARCHAR(40) NULL,
    `CONTAINER_NAME` VARCHAR(40) NULL,
    
    PRIMARY KEY(`PORT`)
) ENGINE=InnoDB AUTO_INCREMENT=1024 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SERVER_INFO` (
	`ID` INT AUTO_INCREMENT NOT NULL,
	`HOST` VARCHAR(15),
    `ADMIN_USERNAME` VARCHAR(20),
    `ADMIN_PASSWORD` VARCHAR(20),
    `ADMIN_PORT` INT,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `SERVER_INFO` (`HOST`, `ADMIN_USERNAME`, `ADMIN_PASSWORD`, `ADMIN_PORT`) VALUE ('3.138.141.36', 'ubuntu', 'vy@3a/se', 22);